wydblog/account/urls.py
from django.urls import path,reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name='account'
urlpatterns=[
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='registration/logout.html'),name='logout'),
    path('password_change/',auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html',success_url=reverse_lazy('account:password_change_done')),name='password_change'),
    path('password_change_done/',auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),name='password_change_done'),
    path('register/',views.register,name='register'),

    ]


#Django 内置的登录、修改密码、找回密码等视图函数对应的 URL 模式位于
    #django.contrib.auth.urls.py 中，首先在工程的 urls.py 文件里包含这些 URL 模式
    #将 django.contrib.auth.urls.py 包含进来

#^users/login/$ [name='login']
#^users/logout/$ [name='logout']
#^users/password_change/$ [name='password_change']
#^users/password_change/done/$ [name='password_change_done']
#^users/password_reset/$ [name='password_reset']
#^users/password_reset/done/$ [name='password_reset_done']
#^users/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$ [name='password_reset_confirm']
#^users/reset/done/$ [name='password_reset_complete']

wydblog/blog/urls.py
from django.urls import path
from .import views
app_name='blog'
urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    path('index/',views.IndexView.as_view(),name='index'),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='detail'),
    path('archives/<int:year>/<int:month>/', views.ArchivesView.as_view(), name='archives'),
    path('category/<int:pk>/',views.CategoryView.as_view(),name='category'),
    path('tag/<int:pk>/',views.TagView.as_view(),name='tag'),
]

wydblog/comments/urls.py
from django.urls import path
from . import views
app_name='comments'
urlpatterns=[
    path('comment/post/<int:post_id>/',views.post_comment,name='post_comment'),

]

wydblog/wydblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('blog.urls')),
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('comment/',include('comments.urls')),
    path('search/',include('haystack.urls')),
    path('account/',include('account.urls')),
    path('password-reset/', include('password_reset.urls')),
]

wydblog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
import markdown
from django.utils.html import strip_tags


class Category(models.Model):
    name=models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Tag(models.Model):
    name=models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Post(models.Model):
    title=models.CharField(max_length=100)
    body=models.TextField()
    excerpt = models.CharField(max_length=200, blank=True)

    created_time=models.DateTimeField()
    modified_time=models.DateTimeField()

    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    tags=models.ManyToManyField(Tag,blank=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    class Meta:
        ordering=('-created_time',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})
# Create your models here.

wydblog/comments/models.py
from django.db import models

class Comment(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField(max_length=255)
    url=models.URLField(blank=True)
    text=models.TextField()
    created_time=models.DateTimeField(auto_now_add=True)
    post=models.ForeignKey('blog.Post',on_delete='CASCADE')

    class Meta:
        ordering=('-created_time',)

    def __str__(self):
        return self.text[:20]


# Create your models here.

wydblog/blog/views.py
import markdown
from django.shortcuts import render,get_object_or_404
from .models import Post,Category,Tag
from comments.form import CommentForm
from django.views.generic import ListView,DetailView
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.db.models import Q

class IndexView(ListView):
    model=Post
    template_name='blog/index.html'
    context_object_name='post_list'
    paginate_by=5
    def get_context_data(self,**kwargs):
        '''
        在视图函数中将模板变量传递给模板是通过render函数的context参数传递字典实现，
        在类视图中，这个需要传递的模板变量字典是通过get_context_data获得的，
        所以复写该方法，以便插入自定义的模板变量
        '''
        #获得父类生成的传递给模板的字典
        context = super().get_context_data(**kwargs)
        #父类模板中已经有 paginator,page_obj,is_paginated 这三个模板变量
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页
        #由于context是一个字典，调用get方法从中获取某个键对应的值
        paginator=context.get('paginator')
        page=context.get('page_obj')
        is_paginated=context.get('is_paginated')
        #调用自己写的pagination_data方法获得分页导航栏需要的数据
        pagination_data=self.pagination_data(paginator,page,is_paginated)
        #将分页导航条的模板变量更新到 context 中，pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)
        return context
    def pagination_data(self,paginator,page,is_paginated):
        if not is_paginated:
            return {}
        left=[]
        right=[]
        left_has_more=False
        right_has_more=False
        first=False
        last=False

        page_number=page.number
        total_pages=paginator.num_pages
        page_range=paginator.page_range

        left=page_range[(page_number-3) if (page_number-3)>0 else 0:(page_number-1) if (page_number-1)>0 else 0]
        right=page_range[page_number:page_number+2]
        if right:
            if right[-1] < total_pages - 1:
                right_has_more=True
            if right[-1] < total_pages:
                last=True
        if left:
            if left[0]>2:
                left_has_more=True
            if left[0]>1:
                first=True

        data={
            'left':left,
            'right':right,
            'left_has_more':left_has_more,
            'right_has_more':right_has_more,
            'first':first,
            'last':last,
        }
        return data






'''
def index(request):
    post_list=Post.objects.all()
    return render(request,'blog/index.html',context={'post_list':post_list})
'''


class ArchivesView(IndexView):
    def get_queryset(self):
        year=self.kwargs.get('year')
        month=self.kwargs.get('month')
        return super(ArchivesView,self).get_queryset().filter(created_time__year=year,created_time__month=month)

'''
def archives(request,year,month):
    post_list=Post.objects.filter(created_time__year=year,created_time__month=month)
    return render(request,'blog/index.html',context={'post_list':post_list})
'''

class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)
    #从URL捕获的命名组参数值保存在实例的kwargs属性里（是一个字典），非命名组参数值保存在实例的args属性里（是一个列表）

'''
def category(request,id):
    cate=get_object_or_404(Category,id=id)
    post_list=Post.objects.filter(category=cate)
    return render(request,'blog/index.html',context={'post_list':post_list})
'''

class TagView(IndexView):
    def get_queryset(self):
        tag=get_object_or_404(Tag,pk=self.kwargs.get('pk'))
        return super(TagView,self).get_queryset().filter(tags=tag)


class PostDetailView(DetailView):
    model=Post
    template_name='blog/detail.html'
    context_object_name='post'
    #文章阅读量增加
    def get(self,request,*args,**kwargs):
        #get方法返回的是一个HttpResponse实例
        #先调用父类的get方法后，才有self.object属性，其值为Post模型实例，及被访问的文章post
        response=super(PostDetailView,self).get(request,*args,**kwargs)
        self.object.increase_views()
        #视图必须返回一个HttpResponse对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super(PostDetailView, self).get_object(queryset=None)
        md=markdown.Markdown(
            extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',  #代码高亮拓展
                TocExtension(slugify=slugify),    #自动生成目录
            ]
        )
        post.body=md.convert(post.body)
        post.toc=md.toc
        return post


    def get_context_data(self,**kwargs):
        #把评论表单和post的评论列表传递给模板
        context=super(PostDetailView, self).get_context_data(**kwargs)
        form=CommentForm()
        comment_list=self.object.comment_set.all()
        context.update({
            'form':form,
            'comment_list':comment_list
        })
        return context

def search(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = "请输入关键词"
        return render(request, 'blog/index.html', {'error_msg': error_msg})

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'error_msg': error_msg,
                                               'post_list': post_list})





'''
def detail(request, id):
    post = get_object_or_404(Post, id=id)
    post.increase_views()
    # 记得在顶部引入 markdown 模块
    post.body = markdown.markdown(post.body,
                                  extensions=[
                                     'markdown.extensions.extra',
                                     'markdown.extensions.codehilite',
                                     'markdown.extensions.toc',
                                  ])
    form=CommentForm()
    comment_list=post.comment_set.all()
    context={
        'post':post,
        'form':form,
        'comment_list':comment_list,
    }
    return render(request, 'blog/detail.html', context=context)
'''

# Create your views here.

wydblog/templates/blog/detail.html
{% extends 'base.html' %}





{% block main %}
                <article class="post post-{{post.id}}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{post.title}}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{post.category.name}}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{post.created_time}}">{{post.created_time}}</time></a></span>
                            <span class="post-author"><a href="#">{{post.author}}</a></span>
                            <span class="comments-link"><a href="#">{{post.comment_set.count}} 评论</a></span>
                            <span class="views-count"><a href="#">{{post.views}} 阅读</a></span>
                        </div>

                    </header>
                    <div class="entry-content clearfix">
                        {{post.body|safe}}
                        <div class="widget-tag-cloud">
                            <ul>
                                标签：
                                {% for tag in post.tags.all %}
                                    <li><a href="{% url 'blog:tag' tag.pk %}"> # {{ tag.name }}</a></li>

                                {% endfor %}
                            </ul>
                       </div>
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.id %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.name.id_for_label }}">名字：</label>
                                {{form.name}}
                                {{form.name.errors}}

                            </div>
                            <div class="col-md-4">
                                <label for="{{form.email.id_for_lable}}">邮箱：</label>
                                {{form.email}}
                                {{form.email.errors}}
                            </div>
                            <div class="col-md-4">
                                <label for="{{form.url.id_for_table}}">网址：</label>
                                {{form.url}}
                                {{form.url.errors}}
                            </div>
                            <div class="col-md-12">
                                <label for="{{form.url.id_for_table}}">评论：</label>
                                {{form.text}}
                                {{form.text.errors}}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{post.comment_set.count}}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{comment.name}}</span>
                                <time class="submit-date" datetime="{{comment.created_time}}">{{comment.created_time}}</time>
                                <div class="text">
                                    {{comment.text}}
                                </div>
                            </li>
                            {% empty %}
                            暂无评论
                            {% endfor %}
                        </ul>
                    </div>
                </section>
            {% endblock main %}
            {% block toc %}
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    {{ post.toc|safe }}
                </div>
{% endblock toc %}

wydblog/templates/blog/index - 副本.html
{% extends 'base.html' %}
{% block main %}
{% load blog_tags %}

{% if error_msg %}
    <p>{{ error_msg }}</p>
  {% endif %}
                {% for post in post_list %}
                <article class="post post-{{post.id}}">
                    <div class="home-post well clearfix">
                        <div class="post-title underline clearfix">
                            <a href="{{post.get_absolute_url}}"></a>

                            <h3>
                                <strong><a href="{{post.get_absolute_url}}">{{post.title}}</a></strong>
                            </h3>

                            <div class="post-info">
                                <span>
                                    <span class="glyphicon glyphicon-calendar"></span>
                                    {{ post.created_time }}
                                </span>
                                <span>
                                    <span class="glyphicon glyphicon-comment"></span>
                                    {{post.comment_set.count}}
                                </span>
                                <span>
                                    <span class="glyphicon glyphicon-eye-open"></span>
                                    {{ post.views }}
                                </span>
                                <div class="post-tags">

                                        {% get_tags as tag_list %}
                                            <ul>
                                                {% for tag in tag_list %}
                                                <li>
                                                    <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                                                </li>
                                                {% empty %}
                                                暂无标签
                                                {% endfor %}
                                            </ul>
                                </div>

                            </div>
                        </div>
                        <div class="post-content">
                            <div class="row">


                                <div class="col-md-6">
                                    <a href="/article/71/">
                                        <p>
                                            {{ post.excerpt }}...
                                        </p>
                                    </a>
                                </div>
                                <div class="col-md-2">
                                    <a type="button" class="btn btn-raised btn-info"
                                       style="float:right;margin-top: 6px;margin-right: 6px" href="{{post.get_absolute_url}}">阅读全文</a>

                                </div>
                            </div>
                        </div>
                    </div>
                    </article>
              <!--  {% empty %}
                <div class="no-post">暂时还没有文章</div>
                {% endfor %}-->










<!--
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{post.category.name}}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{post.author}}</a></span>
                            <span class="comments-link"><a href="#">{{post.comment_set.count}} 评论</a></span>
                            <span class="views-count"><a href="{{post.get_absolute_url}}">{{post.views}} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.excerpt }}...</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{post.get_absolute_url}}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% empty %}
                <div class="no-post">暂时还没有文章</div>
                {% endfor %}
-->


                <div class="text-center">
                {% if is_paginated %}
                <div class="pagination">
                    {% if first %}
                    <a href="?page=1">1</a>
                    {% endif %}
                    {% if left %}
                        {% if left_has_more %}
                            <span>...</span>
                        {% endif %}
                        {% for i in left %}
                            <a href="?page={{i}}">{{i}}</a>
                        {% endfor %}
                    {% endif %}
                    <a class="current-page" href="?page={{ page_obj.number }}" >{{ page_obj.number }}</a>
                    {% if right %}
                        {% for i in right %}
                            <a href="?page={{i}}">{{i}}</a>
                        {% endfor %}
                        {% if right_has_more %}
                            <span>...</span>
                        {% endif %}
                    {% endif %}
                    {% if last %}
                    <a href="?page={{paginator.num_pages}}">{{paginator.num_pages}}</a>
                    {% endif %}
                </div>
                {% endif %}
                    </div>


{% endblock main %}

wydblog/templates/blog/index.html
{% extends 'base.html' %}

{% block add %}

{% if user.is_authenticated %}
<li class="cl-effect-11"><a href="#" data-hover="{{user.username}}">{{user.username}}</a></li>

<li class="cl-effect-11"><a href="{% url 'account:logout' %}?next={{request.path}}" data-hover="退出">退出</a></li>
<li class="cl-effect-11"><a href="{% url 'account:password_change' %}?next={{request.path}}" data-hover="修改密码">修改密码</a></li>

{% else %}
<li class="cl-effect-11"><a href="{% url 'account:login' %}?next={{request.path}}" data-hover="登录">登录</a></li>
{% endif %}

{% endblock add %}

{% block main %}
{% load blog_tags %}

{% if error_msg %}
    <p>{{ error_msg }}</p>
  {% endif %}
                {% for post in post_list %}
                <article class="post post-{{post.id}}">
                    <div class="home-post well clearfix">
                        <div class="post-title underline clearfix">
                            <a href="{{post.get_absolute_url}}"></a>

                            <h3>
                                <strong><a href="{{post.get_absolute_url}}">{{post.title}}</a></strong>
                            </h3>

                            <div class="post-info">

                                <span>

                                    <i class="iconfont icon-icon_calendar"></i>
                                    {{ post.created_time }}
                                </span>
                                <span>
                                    <i class="iconfont icon-icon_sms"></i>
                                    {{post.comment_set.count}}
                                </span>
                                <span>
                                    <span class="iconfont icon-liulan"></span>
                                    {{ post.views }}
                                </span>
                                <div class="post-tags">

                                        {% get_tags as tag_list %}
                                            <ul>
                                                {% for tag in tag_list %}
                                                <li>
                                                    <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                                                </li>
                                                {% empty %}
                                                暂无标签
                                                {% endfor %}
                                            </ul>
                                </div>

                            </div>
                        </div>
                        <div class="post-content">
                            <div class="row">


                                <div class="col-md-6">
                                    <a href="/article/71/">
                                        <p>
                                            {{ post.excerpt }}...
                                        </p>
                                    </a>
                                </div>
                                <div class="col-md-2">
                                    <a type="button" class="btn btn-raised btn-info"
                                       style="float:right;margin-top: 6px;margin-right: 6px" href="{{post.get_absolute_url}}">阅读全文</a>

                                </div>
                            </div>
                        </div>
                    </div>
                    </article>
                {% empty %}
                <div class="no-post">暂时还没有文章</div>
                {% endfor %}

                <div class="text-center">
                {% if is_paginated %}
                <div class="pagination">
                    {% if first %}
                    <a href="?page=1">1</a>
                    {% endif %}
                    {% if left %}
                        {% if left_has_more %}
                            <span>...</span>
                        {% endif %}
                        {% for i in left %}
                            <a href="?page={{i}}">{{i}}</a>
                        {% endfor %}
                    {% endif %}
                    <a class="current-page" href="?page={{ page_obj.number }}" >{{ page_obj.number }}</a>
                    {% if right %}
                        {% for i in right %}
                            <a href="?page={{i}}">{{i}}</a>
                        {% endfor %}
                        {% if right_has_more %}
                            <span>...</span>
                        {% endif %}
                    {% endif %}
                    {% if last %}
                    <a href="?page={{paginator.num_pages}}">{{paginator.num_pages}}</a>
                    {% endif %}
                </div>
                {% endif %}
                    </div>


{% endblock main %}