wydblog/account/urls.py
from django.urls import path,reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name='account'
urlpatterns=[
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='registration/logout.html'),name='logout'),
    path('password_change/',auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html',success_url=reverse_lazy('account:password_change_done')),name='password_change'),
    path('password_change_done/',auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),name='password_change_done'),
    path('register/',views.register,name='register'),

    ]


#Django 内置的登录、修改密码、找回密码等视图函数对应的 URL 模式位于
    #django.contrib.auth.urls.py 中，首先在工程的 urls.py 文件里包含这些 URL 模式
    #将 django.contrib.auth.urls.py 包含进来

#^users/login/$ [name='login']
#^users/logout/$ [name='logout']
#^users/password_change/$ [name='password_change']
#^users/password_change/done/$ [name='password_change_done']
#^users/password_reset/$ [name='password_reset']
#^users/password_reset/done/$ [name='password_reset_done']
#^users/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$ [name='password_reset_confirm']
#^users/reset/done/$ [name='password_reset_complete']

wydblog/blog/urls.py
from django.urls import path
from .import views
app_name='blog'
urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    path('index/',views.IndexView.as_view(),name='index'),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='detail'),
    path('archives/<int:year>/<int:month>/', views.ArchivesView.as_view(), name='archives'),
    path('category/<int:pk>/',views.CategoryView.as_view(),name='category'),
    path('tag/<int:pk>/',views.TagView.as_view(),name='tag'),
]

wydblog/wydblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('blog.urls')),
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('comment/',include('comments.urls')),
    path('search/',include('haystack.urls')),
    path('account/',include('account.urls')),
    path('password-reset/', include('password_reset.urls')),
]

wydblog/templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>鱼蛋的博客</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->

    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}"><!--引入Markdown里代码高亮的样式文件-->
    <link rel="stylesheet" href="{% static 'blog/css/iconfont/iconfont.css' %}">


    <style>
        span.highlighted {
            color: red;
        }
    </style>
    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>WYD</b>. Jokme.</a></h1>

                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="关于">关于</a></li>
                            <!--
                            {% if user.is_authenticated %}
                            <li class="cl-effect-11"><a href="#" data-hover="{{user.username}}">{{user.username}}</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="退出">退出</a></li>
                            {% else %}
                            <li class="cl-effect-11"><a href="#" data-hover="{% url 'account:login' %}?next={% url 'blog:index' %}">登录</a></li>

                            {% endif %}
                            -->
{% block add %}
{% endblock add %}

                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="搜索">
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
               {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %} <!--as语法，将获取的文章存入recent_post_list模板变量中-->
                    <ul>
                         {% for post in recent_post_list %}
                        <li>
                             <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                        </li>
                        {% empty %}
                        暂无文章
                        {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">{{date.year}} 年 {{date.month}} 月<span class="post-count"></span></a>
                        </li>
                        {% empty %}
                        <div>暂无归档</div>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.id %}">{{category.name}}<span class="post-count">({{category.num_posts}})</span></a>
                        </li>
                        {% empty %}
                        暂无分类！
                        {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% empty %}
                        暂无标签
                        {% endfor %}
                    </ul>
                </div>

            </aside>
        </div>
    </div>
</div>

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">鱼蛋的博客</p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            <li><a href="#">博客</a></li>
            <li><a href="#">关于</a></li>
            <li><a href="#">联系</a></li>
        </ul>
    </nav>
</div>



<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>